# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-GB"
title                    : "Ben Seymour"
title_separator          : "-"
name                     : "Oxford U.K. - eCommerce & Dynamic Content Specialist, Responsive Images Advocate"
description              : "The core online presence of Ben Seymour (Oxford, U.K.)"
url                      : "https://mra.benseymour.com" # the base hostname & protocol for your site 
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : bseymour/bseymour.github.io # GitHub username/repo-name
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: 
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
image_url: "/images"
amp_base: "//i1.adis.ws/i/bendemo"
cloudinary_base: "//images.benseymour.com/image/upload/"
default_width: '1000'
sizes: "(min-width: 1020px) 60vw, 90vw"
srcset:
- 600
- 850
- 1200
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter: username               :bseymour
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: google
  google:
    tracking_id: UA-6520077-12
author:
  name: Ben Seymour
  avatar: profile-pics-bw-oct2018-sq.jpg
  bio: eCommerce & Dynamic Content Specialist | Responsive Images Advocate | Author
    | Husband & Dad | Code Club | Motorsports & cycling | though not in that order...
  location: Oxford, U.K.
  email: 
  uri: 
  bitbucket: 
  codepen: bseymour
  dribbble: 
  flickr: boseymour
  facebook: 
  foursquare: 
  github: bseymour
  google_plus: "BenSeymour"
  keybase: 
  instagram: boseymour
  lastfm: 
  linkedin: benseymour
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: bseymour
  vine: 
  weibo: 
  xing: 
  youtube: 
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
